title: ntheanh201
subtitle: 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ntheanh201.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: ntheanh201  #for comments using disqus
author: ntheanh201
author_bio: 
author_email: "ntheanh201@gmail.com"
author_location: Vietnam
author_website_url: "https://ntheanh201.github.io"

# social links
twitter_username: ntheanh201
github_username:  ntheanh201
facebook_username: ntheanh201
linkedin_username: yourusername
behance_username: yourusername
instagram_username: ntheanh201
medium_username: yourusername 
telegram_username: yourusername
dribbble_username: yourusername 
flickr_username: yourusername