title: Cayman Blog Theme
description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and GitHub Pages, with social/SEO features.
show_downloads: true

baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://lorepirri.github.io" # change this to the base hostname & protocol for your site

<<<<<<< HEAD
=======
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: 
author:
  name: Nguyễn Thế Anh
  email: ntheanh201@gmail.com 
  github: ntheanh201
  twitter: 
  pinterest: 
  linkedin:
  bio: PTIT
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
=======
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Nguyễn Thế Anh

# Short bio or description (displayed in the header)
description: Student from PTIT

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: ntheanh201@gmail.com
  facebook: fb.com/ntheanh201
  flickr:
  github: ntheanh201
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
>>>>>>> a120f893488b2622aac81e48676e98f203766e43
google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Lore Pirri"
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
