# Website details
name: Kinn
description: Góc nhỏ cho những câu chuyện xàm xí của Thế Anh
email: ntheanh201@gmail.com
author: Kinn
lang: en
locale: en_US

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/New_York
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: https://ntheanh201.github.io

# Includes
addthisId: ""
disqusUsername: "ntheanh201"
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"
